examples/credit-card-example/credit-card-example.html, examples/credit-card-example/credit-card-example.js, examples/login-data-example/login-data-example.html, examples/login-data-example/login-data-example.js, examples/pii-example/pii-example.html, examples/pii-example/pii-example.js, examples/shipping-info-example/shipping-info-example.html, examples/shipping-info-example/shipping-info-example.js
- Created a folder with examples for the following use cases:
1. Credit Card Example
2. Login Example
3. Shipping Info Example
4. PII Example
- Added explaining comments to .html and .js examples files
=> Structure folders in use case examples

index.html, js/credit-card-example.js, js/login-data-example.js, js/pii-example.js, js/shipping-info-example.js
CH Story
https://app.clubhouse.io/vgs/story/15373/complete-implement-real-tokenization-to-examples-site
- add a new library for examples
- add tokenization for credit card example (https://dashboard.verygoodsecurity.com/dashboard/v/VLTdkZQhBxjWAhXocGzm3Lo29/routes/a93cc6cc-463a-497a-a4ab-4f4051031213/edit)
=> add new lib for tokenization

index.html
- Added links for the code example
=> Structure folders in use case examples [ch15237]

README.md
- Changed repository description markdown
=> Update VGS Collect Examples repository markdown

css/style.css, index.html, js/credit-card-example.js, js/login-data-example.js, js/pii-example.js, js/script.js, js/shipping-info-example.js
[16532](https://app.clubhouse.io/vgs/story/16532/vgs-collect-examples-improvements-part-1)
- Added UI error validation
- Changed response window inner text
=> VGS Collect examples improvements Part 1

css/style.css, index.html
Fixed [18152](https://app.clubhouse.io/vgs/story/18152/information-icon-is-not-clickable-on-mobile-view)
=> Information icon is not clickable on mobile [ch18152]

examples/credit-card-example/README.md, examples/credit-card-example/credit-card-example.html
=> Step by step guide - credit card

examples/credit-card-example/README.md, examples/login-data-example/README.md, examples/login-data-example/login-data-example.html, examples/pii-example/README.md, examples/pii-example/pii-example.html, examples/shipping-info-example/README.md, examples/shipping-info-example/shipping-info-example.html
Fixes [19676](https://app.clubhouse.io/vgs/story/19676/code-examples-step-by-step-guide)
- Added step by step guide for code examples
=> Code examples step by step guide

examples/credit-card-example/credit-card-example.html, examples/login-data-example/login-data-example.html, examples/pii-example/pii-example.html, examples/shipping-info-example/shipping-info-example.html
Fixes [19685](https://app.clubhouse.io/vgs/story/19685/clean-code-example-files)
=> Clean code example files

examples/login-data-example/login-data-example.html, examples/pii-example/pii-example.html, examples/shipping-info-example/shipping-info-example.html
Fixes [19729](https://app.clubhouse.io/vgs/story/19729/fix-form-initialization-in-code-examples)
=> Fix form initialization in code examples [ch19729]

examples/credit-card-example/README.md, examples/login-data-example/README.md, examples/pii-example/README.md, examples/shipping-info-example/README.md
Fixes [19804](https://app.clubhouse.io/vgs/story/19804/improve-markdown-in-code-examples)
- Added one step to the markdown
=> Improve markdown in code examples [ch19804]

examples/credit-card-example/credit-card-example.html, examples/login-data-example/login-data-example.html, examples/pii-example/pii-example.html, examples/shipping-info-example/shipping-info-example.html
=> Improve Examples with Pavolve recomendations [ch20402]

css/style.css, examples/credit-card-example/credit-card-example.html, examples/login-data-example/login-data-example.html, examples/pii-example/pii-example.html, examples/shipping-info-example/shipping-info-example.html, index.html
Fixes [22539](https://app.clubhouse.io/vgs/story/22539/add-more-styles-for-example-page)
- Changed 'Learn more' button text
- 'Code examples' button highlighted
- Code exampled improved
=> Add more styles for example page [ch22539]

js/credit-card-example.js, js/login-data-example.js, js/pii-example.js, js/script.js, js/shipping-info-example.js
=> Fix site with examples in IE [ch22538]

css/style.css, examples/credit-card-example/credit-card-example.html, examples/login-data-example/login-data-example.html, examples/pii-example/pii-example.html, examples/shipping-info-example/shipping-info-example.html, index.html
- Changed link path from .io to .com
- Fixed fonts CORS issue
=> Change links to com js library instead of [ch23320]

css/style.css, index.html, style_examples.html, styles_examples/credit-card-custom.js, styles_examples/login-form-custom.js, styles_examples/pii-form-custom.js, styles_examples/shipping-form-custom.js
- Styles feature initial design
=> Design form for css feature on examples page

examples/credit-card-example/credit-card-example.html, examples/login-data-example/login-data-example.html, examples/pii-example/pii-example.html, examples/shipping-info-example/shipping-info-example.html
Fixes [26298](https://app.clubhouse.io/vgs/story/26298/vgs-collect-response-examples-have-hardcoded-cc-response)
- Hardcoded phrase removed.
=> VGS collect response examples have hardcoded [ch26298]

index.html
- Link to 'style examples' is now available.
=> Show styles link

css/style.css, style-examples.html
Fixes [27772](https://app.clubhouse.io/vgs/story/27772/vgs-collect-implement-new-styles-on-examples-page)
Created responsive page
=> Adapt page for mobile and tablet

README.md, index.html, style-examples.html
Fixes [32889](https://app.clubhouse.io/vgs/story/32889/vgs-collect-update-vgs-collect-to-docs)
=> VGS Collect Update VGS Collect to docs [ch32889]

examples/credit-card-example/credit-card-example.html, js/credit-card-example.js, styles-examples/credit-card-custom.js
- fixed exp date placeholder from 2016 to 2022 year
=> Date placeholder update

css/style.css, index.html, masked-examples.html, masked-examples/masked-examples.js, style-examples.html
Fixes [39869](https://app.clubhouse.io/vgs/story/39869/vgs-collect-add-mask-examples-to-vgs-collect-examples-page)
=> VGS Collect Add mask examples to VGS Collect [ch39869]

css/style.css, index.html, masked-examples.html, style-examples.html
Fixes [41370](https://app.clubhouse.io/vgs/story/41370/vgs-collect-open-mask-examples-for-users)
=> VGS Collect Open mask examples for users [ch41370]

dev.html
[42895](https://app.clubhouse.io/vgs/story/42895/vgs-collect-simplify-test-dev-env)
Create a page with dev file
=> add page with dev file

dev.html, examples/credit-card-example/README.md, examples/credit-card-example/credit-card-example.html, examples/login-data-example/README.md, examples/login-data-example/login-data-example.html, examples/pii-example/README.md, examples/pii-example/pii-example.html, examples/shipping-info-example/README.md, examples/shipping-info-example/shipping-info-example.html, index.html, js/credit-card-example.js, js/login-data-example.js, js/pii-example.js, js/shipping-info-example.js, masked-examples.html, masked-examples/masked-examples.js, style-examples.html, styles-examples/credit-card-custom.js, styles-examples/payment-form-custom.js, styles-examples/pii-form-custom.js, styles-examples/signup-form-custom.js
[47989](https://app.clubhouse.io/vgs/story/47989/vgs-collect-update-examples-for-vgs-collect-js-2-0)
=> Update links to use vgs-collect 2.0

examples/credit-card-example/README.md, examples/credit-card-example/credit-card-example.html, examples/login-data-example/README.md, examples/login-data-example/login-data-example.html, examples/pii-example/README.md, examples/pii-example/pii-example.html, examples/shipping-info-example/README.md, examples/shipping-info-example/shipping-info-example.html
=> rollback examples

examples/credit-card-example/README.md, examples/pii-example/README.md, examples/shipping-info-example/README.md, examples/v2/credit-card-example/README.md, examples/v2/credit-card-example/credit-card-example.html, examples/v2/login-data-example/README.md, examples/v2/login-data-example/login-data-example.html, examples/v2/pii-example/README.md, examples/v2/pii-example/pii-example.html, examples/v2/shipping-info-example/README.md, examples/v2/shipping-info-example/shipping-info-example.html
Fixes [78834](https://app.clubhouse.io/vgs/story/78834/collectjs-add-collect-2-0-examples-to-vgs-collect-examples-repo)
=> Add examples for Collect v2

css/style.css, style-examples.html
=> fix styles

examples/v2/credit-card-example/credit-card-example.html, examples/v2/login-data-example/login-data-example.html, examples/v2/pii-example/pii-example.html, examples/v2/shipping-info-example/shipping-info-example.html, index.html, masked-examples.html, style-examples.html
- add <titles /> to some html files
=> deps: update Collect.js version to 2.5.0

examples/v2/multiplexing/README.md, examples/v2/multiplexing/inbound.yaml, examples/v2/multiplexing/multiplexing.html
- Added more description
- Added flow diagram
- Added Inbound Route template
=> Collect multiplexing demo

dev.html, examples/features/input-masking-example/index.html, index.html, masked-examples.html, style-examples.html
Fonts are missing by the URL we have now, quick temporary fix
=> hotfix: use archived styles

js/credit-card-example.js, js/script.js, js/shipping-info-example.js
Signed-off-by: flor-master <Alexandr.Florinskij@yandex.ua>
=> remove innerHTML

dev.html, examples/customization/floating-labels-example/index.html, examples/customization/single-line-payment-form-example/single-line-payment-example.html, examples/features/capture-bin-number-example/index.html, examples/features/compare-field-values-example/index.html, examples/features/conditional-rendering-example/index.html, examples/features/extended-card-brands-support-example/index.html, examples/features/submit-on-enter-example/index.html, examples/usecases/credit-card-example/credit-card-example.html, examples/usecases/login-data-example/login-data-example.html, examples/usecases/multiplexing-example/multiplexing.html, examples/usecases/pii-example/pii-example.html, examples/usecases/shipping-info-example/shipping-info-example.html, index.html, masked-examples.html, style-examples.html
- Update the Collect.js version to the latest.
=> Update collect version
